[versions]
compile-sdk = "34"
min-sdk = "24"
target-sdk = "34"
version-code = "1"
version-name = "1"

agp = "8.2.1"
kotlin = "1.9.0"
core-ktx = "1.12.0"
kotlin-compiler-extension-version = "1.5.1"
junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
lifecycle-runtime-ktx = "2.7.0"
activity-compose = "1.8.2"
compose-bom = "2024.02.00"
material = "1.11.0"
coilCompose = "2.5.0"
coroutines = "1.8.0"
lifecycle-viewmodel-compose = "2.7.0"
navigationCompose = "2.7.7"
hilt = "2.50"
androidx-paging = "3.2.1"
androidx-paging-compose = "3.3.0-alpha03"
retrofit = "2.9.0"
http-logging-interceptor = "4.12.0"
moshi = "1.15.1"
moshi-retrofit-converter = "2.9.0"
ksp = "1.9.0-1.0.13"
hilt-navigation-compose = "1.2.0"
lifecycle-runtime-compose = "2.7.0"
mockk = "1.13.9"
androidx-arch-testing = "2.2.0"
turbine = "1.0.0"
assertj = "3.25.3"


[libraries]
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
material3 = { group = "androidx.compose.material3", name = "material3" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle-viewmodel-compose" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
androidx-paging = { module = "androidx.paging:paging-runtime", version.ref = "androidx-paging" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "androidx-paging-compose" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
http-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "http-logging-interceptor" }
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-retrofit-converter = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "moshi-retrofit-converter" }
moshi-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation-compose" }
lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle-runtime-compose" }

mockk-test = { module = "io.mockk:mockk", version.ref = "mockk" }
courintes-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
androidx-arch-testing = { module = "androidx.arch.core:core-testing", version.ref = "androidx-arch-testing" }
androidx-paging-testing = { module = "androidx.paging:paging-common", version.ref = "androidx-paging" }
turbine-testing = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

